/**
 * Generates:
 *   - src/generated/episodes.ts     → registry used by Remotion Studio (one composition per episode)
 *   - episodes/episode.schema.json  → JSON Schema for editor autocomplete/validation
 *
 * Invalid episodes are still registered so Studio can show a readable error screen.
 */
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { z } from "zod";
import { EpisodeSchema } from "../src/schema/episode";
import { EpisodeError, listEpisodeIds, loadEpisode } from "./lib/episodes";
import { EPISODES_DIR, GENERATED_DIR } from "./lib/paths";

export function syncEpisodes({ quiet = false } = {}) {
  const entries = listEpisodeIds().map((id) => {
    try {
      const { episode } = loadEpisode(id);
      return { id, episode, errors: [] as string[] };
    } catch (err) {
      const errors = err instanceof EpisodeError ? err.problems : [(err as Error).message];
      return { id, episode: null, errors };
    }
  });

  fs.mkdirSync(GENERATED_DIR, { recursive: true });
  const body =
    `// AUTO-GENERATED by scripts/sync-episodes.ts — do not edit. Run \`npm run sync\`.\n` +
    `import type { EpisodeRegistryEntry } from "../engine/types";\n\n` +
    `export const EPISODES: EpisodeRegistryEntry[] = ${JSON.stringify(entries, null, 2)};\n`;
  fs.writeFileSync(path.join(GENERATED_DIR, "episodes.ts"), body);

  const jsonSchema = z.toJSONSchema(EpisodeSchema, { io: "input", unrepresentable: "any" });
  fs.writeFileSync(path.join(EPISODES_DIR, "episode.schema.json"), JSON.stringify(jsonSchema, null, 2) + "\n");

  if (!quiet) {
    for (const e of entries) {
      if (e.errors.length) {
        console.log(`  ✗ ${e.id}`);
        for (const p of e.errors) console.log(`      ${p}`);
      } else {
        console.log(`  ✓ ${e.id}`);
      }
    }
    console.log(`Synced ${entries.length} episode(s) → src/generated/episodes.ts`);
  }
  return entries;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  syncEpisodes();
}
